- name: Install Docker

  hosts: jenkins

  become: yes
  become_method: sudo

  tasks:

  - name: Check if jenkins folder exists
    stat:
      path: jenkins
    register: jenkins_home

  - name: Clean up docker-compose
    command: >
       docker-compose down
    args:
       chdir: ./jenkins/
    when: jenkins_home.stat.exists

  - name: Delete docker working-dir
    file:
       state: absent
       path: jenkins
    when: jenkins_home.stat.exists

  - name: Copy jenkins working-dir
    synchronize:
       src: ./jenkins/
       dest: jenkins
  - name: Copy certs to load 
    synchronize:
       src: ./jenkins/nginx-config/
       dest: /usr/share/ca-certificates/
  
  - name: load certs for artifactory
    shell: sudo update-ca-certificates

  - name: Generate a Self Signed OpenSSL certificate
    command: >
       openssl req -subj '/CN=jenkins' -x509 -newkey rsa:4096 -nodes
       -keyout jenkins.pem -out jenkins.pem -days 999
    args:
       chdir: ./jenkins/nginx-config/

  - name: Call docker-compose to run jenkins-stake
    command: >
       docker-compose -f docker-compose.yml up -d
    args:
       chdir: ./jenkins/